### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by povolann** [tobias-kirschstein/gghead#28]
Hello, 

I wanted to train the AFHQ dataset, so first I have tried using the pre-trained model, as written in read me (with smaller batch 16, so it would fit in my **GPU RTX 4090**): 
`BW_IMPLEMENTATION=1 python scripts/train_gghead.py ffhq afhq_v2_processed.zip 1 16 --kimg 30000 --resume_run GGHEAD-1_ffhg512`
but I got error
```
tick 0     kimg 23200.0  time 28s          sec/tick 7.2     sec/kimg 450.44  maintenance 21.1   cpumem 2.84   gpumem 19.61  reserved 22.05  augment 0.000
/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py:396: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
/home/anya/Programs/gghead/src/gghead/trained_models/gghead/GGHEAD-7_afhq_v2_processed-gpus1-batch32-gamma1-res512-resumeGGHEAD-1_ffhg512
Evaluating metrics...
Generating images for FID: 100%|##########| 100/100 [00:04<00:00, 38.56it/s]Traceback (most recent call last):
  File "scripts/train_gghead.py", line 719, in <module>
    tyro.cli(main)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/tyro/_cli.py", line 229, in cli
    return run_with_args_from_cli()
  File "scripts/train_gghead.py", line 715, in main
    launch_training(experiment_config, c=c, dry_run=opts.dry_run, name=name)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 115, in launch_training
    subprocess_fn(experiment_config=experiment_config, rank=0, c=c, temp_dir=temp_dir, name=name)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 70, in subprocess_fn
    training_loop(experiment_config, rank=rank, name=name, **c)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 718, in training_loop
    result_dict = calc_metric(metric=metric, G=snapshot_data['G_ema'],
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/eg3d/metrics/metric_main.py", line 51, in calc_metric
    results = _metric_dict[metric](opts)
  File "/home/anya/Programs/gghead/src/gghead/util/metrics.py", line 10, in fid100
    fid = frechet_inception_distance.compute_fid(opts, max_real=100, num_gen=100)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/eg3d/metrics/frechet_inception_distance.py", line 31, in compute_fid
    mu_gen, sigma_gen = metric_utils.compute_feature_stats_for_generator(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/eg3d/metrics/metric_utils.py", line 289, in compute_feature_stats_for_generator
    img = G(z=z, c=next(c_iter), **opts.G_kwargs)['image']
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anya/Programs/gghead/src/gghead/models/gghead_model.py", line 745, in forward
    return self.synthesis(ws, c, update_emas=update_emas, neural_rendering_resolution=neural_rendering_resolution,
  File "/home/anya/Programs/gghead/src/gghead/models/gghead_model.py", line 855, in synthesis
    rendered_image = render(gaussian_camera, self._gaussian_model, PipelineParams2(), gaussian_bg,
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/gaussian_splatting/gaussian_renderer/__init__.py", line 148, in render
    rendered_image, radii, depth_image = rasterizer(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 228, in forward
    return rasterize_gaussians(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 33, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 98, in forward
    num_rendered, num_buckets, color, invdepths, radii, geomBuffer, binningBuffer, imgBuffer, sampleBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "scripts/train_gghead.py", line 719, in <module>
    tyro.cli(main)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/tyro/_cli.py", line 229, in cli
    return run_with_args_from_cli()
  File "scripts/train_gghead.py", line 715, in main
    launch_training(experiment_config, c=c, dry_run=opts.dry_run, name=name)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 115, in launch_training
    subprocess_fn(experiment_config=experiment_config, rank=0, c=c, temp_dir=temp_dir, name=name)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 70, in subprocess_fn
    training_loop(experiment_config, rank=rank, name=name, **c)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 718, in training_loop
    result_dict = calc_metric(metric=metric, G=snapshot_data['G_ema'],
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/eg3d/metrics/metric_main.py", line 51, in calc_metric
    results = _metric_dict[metric](opts)
  File "/home/anya/Programs/gghead/src/gghead/util/metrics.py", line 10, in fid100
    fid = frechet_inception_distance.compute_fid(opts, max_real=100, num_gen=100)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/eg3d/metrics/frechet_inception_distance.py", line 31, in compute_fid
    mu_gen, sigma_gen = metric_utils.compute_feature_stats_for_generator(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/eg3d/metrics/metric_utils.py", line 289, in compute_feature_stats_for_generator
    img = G(z=z, c=next(c_iter), **opts.G_kwargs)['image']
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anya/Programs/gghead/src/gghead/models/gghead_model.py", line 745, in forward
    return self.synthesis(ws, c, update_emas=update_emas, neural_rendering_resolution=neural_rendering_resolution,
  File "/home/anya/Programs/gghead/src/gghead/models/gghead_model.py", line 855, in synthesis
    rendered_image = render(gaussian_camera, self._gaussian_model, PipelineParams2(), gaussian_bg,
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/gaussian_splatting/gaussian_renderer/__init__.py", line 148, in render
    rendered_image, radii, depth_image = rasterizer(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 228, in forward
    return rasterize_gaussians(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 33, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 98, in forward
    num_rendered, num_buckets, color, invdepths, radii, geomBuffer, binningBuffer, imgBuffer, sampleBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I have tried reinstalling the gghead Anaconda environment multiple times, but so far it is the same.
I have also tried running the training code for AFHQ from the start using a smaller batch (16, 8 and 4).
`BW_IMPLEMENTATION=1 python scripts/train_gghead.py ffhq afhq_v2_processed.zip 1 16 --kimg 1600`
Then the code runs longer, but it crashes around tick 80-100 with a similar error
```
Traceback (most recent call last):
  File "scripts/train_gghead.py", line 719, in <module>
    tyro.cli(main)
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/tyro/_cli.py", line 229, in cli
    return run_with_args_from_cli()
  File "scripts/train_gghead.py", line 715, in main
    launch_training(experiment_config, c=c, dry_run=opts.dry_run, name=name)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 115, in launch_training
    subprocess_fn(experiment_config=experiment_config, rank=0, c=c, temp_dir=temp_dir, name=name)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 70, in subprocess_fn
    training_loop(experiment_config, rank=rank, name=name, **c)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/train_loop.py", line 554, in training_loop
    loss.accumulate_gradients(phase=phase.name, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, gain=phase.interval, cur_nimg=cur_nimg)
  File "/home/anya/Programs/gghead/src/gghead/eg3d/loss.py", line 404, in accumulate_gradients
    gen_img, _gen_ws = self.run_G(gen_z, gen_c, swapping_prob=swapping_prob, neural_rendering_resolution=neural_rendering_resolution,
  File "/home/anya/Programs/gghead/src/gghead/eg3d/loss.py", line 141, in run_G
    gen_output = self.G.synthesis(ws, c, neural_rendering_resolution=neural_rendering_resolution, update_emas=update_emas, **synthesis_kwargs)
  File "/home/anya/Programs/gghead/src/gghead/models/gghead_model.py", line 855, in synthesis
    rendered_image = render(gaussian_camera, self._gaussian_model, PipelineParams2(), gaussian_bg,
  File "/home/anya/anaconda3/envs/gghead/lib/python3.8/site-packages/gaussian_splatting/gaussian_renderer/__init__.py", line 185, in render
    "visibility_filter": (radii > 0).nonzero(),
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Just fyi the rendering from the pretrained models works fine.

**Comment by baoachun** [comment]
Perhaps you can check whether any of the Gaussian attributes contain NaN or Inf values, and also verify whether the scale values are excessively large.

**Comment by povolann** [comment]
> Perhaps you can check whether any of the Gaussian attributes contain NaN or Inf values, and also verify whether the scale values are excessively large.

Thank you for your help!

I tried this for all the inputs (`means`, `opacities`, `scales`, `rotations` etc.) for `rasterizer()` in the Gaussian renderer, but the moment I tried to get scales.shape/opacities.shape etc. it works until the moment it crashes and then I get simillar error, but it will crash earlier (on the line when I want to get .shape). So, I am a bit lost on how exactly to see the values inside or which variables to watch.

But let's say it would be a memory problem, do you have an idea which parameters from the Gaussians downsize?

**Comment by baoachun** [comment]
I’ve encountered similar memory issues before, though I’m not sure if it’s exactly the same as yours. Switching to the `gsplat` rendering library might help resolve the problem more efficiently.

You could also try enabling `CUDA_ENABLE_COREDUMP_ON_EXCEPTION`. After running your program, it may generate a log file with the `.nvcudmp` extension, which you can load using `cuda-gdb` to locate the point of failure.

**Comment by stealthysm** [comment]
Got the same error. As suggested switching to `gsplat` worked somewhat but I'm not sure if that's the way It's supposed to be.
I assume diff-gaussian-rasterization might have some problems or cuda compatibility issues?

**Comment by tobias-kirschstein** [comment]
Hi, this is a nasty error to debug remotely...
One guess would be that it comes from the speed optimizations. You can disable them by removing the
`BW_IMPLEMENTATION=1` line in front of the command.

Other than that, apart from stepping through the code with a debugger, my first go to would be to look into the original gaussian splatting repo, if other people had similar issues. E.g., 
https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620

**Comment by povolann** [comment]
Hi,
I am not working much with this code recently, but today I tried running the original GS, with suggestions [from here](https://github.com/graphdeco-inria/gaussian-splatting/issues/923).
After some additional trials, I ended up with this env + the suggested changes in `submodules/simple-knn/simple-knn.cu` and `gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/resterizer_impl.h`

```
name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cuda-toolkit=12.4
  - plyfile
  - python=3.8
  - pip=22.3.1
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pytorch-cuda=12.4
  - gxx_linux-64=10
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
```
(I guess you can use directly the env [from jesstytam](https://github.com/graphdeco-inria/gaussian-splatting/issues/923#issuecomment-2603845111), but I didn't notice the other changes.)
With this installation, the GS training runs without any errors (I tried it only for the lego dataset).

Then I tried to install `gghead` env like it is written in the Setup here, but I changed step 4. like this
- cloning `tobias-kirschstein/gaussian-splatting` locally
`git clone https://github.com/tobias-kirschstein/gaussian-splatting.git /home/anya/gghead/src/gghead/gaussian_splatting --recursive` 
- then in `/home/anya/gghead/src/gghead/gaussian_splatting` updating `environment.yml file` + `simple-knn.cu` + `resterizer_impl.h` files in a similar manner, like I did for the original `graphdeco-inria/gaussian-splatting`
- install the `gaussian_splatting` module via: `pip install -e .` in the file locally.
- and finishing with step 5.
I didn't get any errors during the env installation.

Then I tried running `(BW_IMPLEMENTATION=1) python scripts/train_gghead.py ... ` but I can't compile `bias_act_plugin`.
I was getting a lot of errors like
```
fatal error: crypt.h: No such file or directory    44 | #include <crypt.h>
fatal error: bits/stdint-least.h: No such file or directory    41 | #include <bits/stdint-least.h>
...
```
In some cases, I managed to get over some of these errors by using something like 
```
export CUDAHOSTCXX=/usr/bin/gcc
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
```
before running `(BW_IMPLEMENTATION=1) python scripts/train_gghead.py ... ` but it was not a very clean approach, just trial and error.
I think I messed up properly merging @tobias-kirschstein 's version of `gaussian_splatting` module with the above-mentioned changes. If someone has advice on how to properly make the changes, that would be very helpful.

**Comment by tobias-kirschstein** [comment]
Hi, do you have any indication that the `CUDA error: an illegal memory access was encountered` would come from using CUDA 12? Otherwise, that approach would not help anyways. 
In terms of this `fatal error: crypt.h: No such file or directory    44 | #include <crypt.h>`  error, that just indicates that some libraries were not installed. Usually the environment.yml in my repository already takes care of that, but if you try to install everything for CUDA 12, it may be that the names of the libraries have changed and one needs to figure out which library contains this `cryph.h` file and then install it via conda

**Comment by povolann** [comment]
> Hi, do you have any indication that the `CUDA error: an illegal memory access was encountered` would come from using CUDA 12? Otherwise, that approach would not help anyways.

Not really, I thought since it is related to GPU it might be connected to the CUDA version, but that's it.
Also, I had to reinstall the whole env anyways, so I wanted to try this approach of matching it to env which worked for the original GS code, but I didn't realize that my approach might be wrong from the start, so thanks for pointing that out.

> In terms of this `fatal error: crypt.h: No such file or directory 44 | #include <crypt.h>` error, that just indicates that some libraries were not installed. Usually the environment.yml in my repository already takes care of that, but if you try to install everything for CUDA 12, it may be that the names of the libraries have changed and one needs to figure out which library contains this `cryph.h` file and then install it via conda

Yep, I am kind of aware of this, so I have to reinstall the whole env again. But I will just do it how I did it originally.

**Comment by stealthysm** [comment]
>You can disable them by removing the
BW_IMPLEMENTATION=1 line in front of the command

@tobias-kirschstein thanks for the suggestion.
Judging from your comment and the latest [commit](https://github.com/tobias-kirschstein/gghead/commit/662067055ddba11d7280a367426b56bf8fdd53f0) , we are expected to use `render_distwar` by default?
Actually, I always got `CUDA Error` with the previous [commit](6043d2b) which internally uses `diff-gaussian-rasterization`'s renderer, but after switching to `diff-gaussian-rasterization-distwar`'s renderer, training seems to be working (at least stage 1).

**Comment by tobias-kirschstein** [comment]
@stealthysm So, your issues are resolved by switching to the newest version of the repository? Or did you have to do something specific to "switch to diff-gaussian-rasterization-distwar's renderer"?

**Comment by stealthysm** [comment]
I'm not 100% sure if it was really solved, but so far no error is observed with the latest commit. I will let you know if I get the same error.

> Or did you have to do something specific to "switch to diff-gaussian-rasterization-distwar's renderer"?

Not really. I just updated [the line 22](https://github.com/tobias-kirschstein/gghead/blob/662067055ddba11d7280a367426b56bf8fdd53f0/src/gghead/models/gghead_model.py#L22) which now imports `render_distwar`, and then re-installed `diff-gaussian-rasterization-distwar` with the recommended build option (so I modified [this line](https://github.com/tobias-kirschstein/diff-gaussian-rasterization-distwar/blob/f322d111b7f37e8d74794948196f16018b7007a3/setup.py#L29), just in case).

I still suspect there is something wrong with cub or some other CUDA-related libraries but currently I have no idea what the root cause is.

**Comment by povolann** [comment]
I think the switch to the newest repository, might help with the original `CUDA error: an illegal memory access was encountered` (I didn't try to reinstall the older repository though). But still after the installation the first run doesn't set up PyTorch plugin `"bias_act_plugin"` properly (see further).

I think I was using the latest commit for the `gghead` installation last time, but to be sure (and following the suggestion from @stealthysm ), I have cloned it again, and I have installed the whole env again.
With these changes this time...
1. I changed cuda to `cuda=12.4` in `environment.yml` for gghead 
2. I still used `conda install gxx_linux-64 gcc_linux-64` 
3. `TORCH_CUDA_ARCH_LIST="8.9" pip install gaussian_splatting@git+https://github.com/tobias-kirschstein/gaussian-splatting.git` (since I have a **GPU RTX 4090** as I said before).

But then, when running the `(BW_IMPLEMENTATION=1) python scripts/train_gghead.py ... ` I was still getting the `crypt.h` etc. errors. By using these (to point to the proper places for the libraries):
```
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
export CFLAGS="-I/usr/include/x86_64-linux-gnu"
export CXXFLAGS="-I/usr/include/x86_64-linux-gnu"
export TORCH_CUDA_ARCH_LIST="8.9"
rm -rf ~/.cache/torch_extensions # (this is needed in case you have already tried to run the code before, otherwise not really)
```
I have managed to start training. Now I am training AFHQ from the start.
`BW_IMPLEMENTATION=1 python scripts/train_gghead.py ffhq afhq_v2_processed.zip 1 16 --kimg 1600`
And it works so far - I am at tick tick 106 (so it trains longer than in the original comment).

**Comment by tobias-kirschstein** [comment]
Did you try with CUDA 11? I suspect that the library structure on conda may have changed for CUDA 12 and the crypt.h stuff would require installing another conda CUDA library (I just don't which one). For CUDA 11 it should work with the libraries from the `environment.yml`
Apart from that, the `bias_act_plugin` comes from StyleGAN2 originally. So you may find some pointers in the issues of that repository that could help resolve the issue

**Comment by tobias-kirschstein** [comment]
For example, you can check whether this `crypt.h` file is already somewhere in your conda environment. Maybe one just has to set some additional path then.
If not, it could be that you can install it via `conda install --channel=conda-forge libxcrypt`

**Comment by povolann** [comment]
> Did you try with CUDA 11? I suspect that the library structure on conda may have changed for CUDA 12 and the crypt.h stuff would require installing another conda CUDA library (I just don't which one). For CUDA 11 it should work with the libraries from the `environment.yml` Apart from that, the `bias_act_plugin` comes from StyleGAN2 originally. So you may find some pointers in the issues of that repository that could help resolve the issue

I tried with CUDA 11 today and the training works, but previously it didn't work well with my GPU RTX 4090 (even when I tried to install this env originally in June, but I don't have any notes for that case any more), which is why I use CUDA 12 most of the time.
When I was installing EG3D or similar envs previously, I managed to run them successfully with CUDA 12. I was getting an error for `bias_act_plugin` too, but it always looked like this
_ImportError: /home/anya/anaconda3/envs/triplane/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6: version 'GLIBCXX_3.4.32' not found (required by /home/anya/.cache/torch_extensions/py39_cu124/bias_act_plugin/b46266ff65f9fa53c32108953a1c6f16-nvidia-geforce-rtx-4090/bias_act_plugin.so)_
And then it was enough to `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6` (or include it into `.bashrc`) to solve this. But as you see, I was getting different types of errors this time. And I did check whether the `crypt.h` file is already in my conda env (it was), so I set up the additional paths with the different exports (I think I included all in my previous comment, but I might have missed some...).

_Side note for the installation with CUDA 11: Since I mostly use CUDA 12 in my envs and base env, you have to make sure that you use CUDA from the codna env, not the system one (you can check it with `which nvcc` and `nvcc --version`._

So I think we can close this issue, because I have managed to run the code in both envs (with CUDA 11 or CUDA 12). Some of these comments might be useful for people who would like to use CUDA 12.
